-- AlterTable
ALTER TABLE "Content" ALTER COLUMN "apiDev" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "beSkills" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "db" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "feSkills" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "lang" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "versionCon" SET DEFAULT ARRAY[]::TEXT[];
